export const MenuItems = [
    { title: 'Dashboard', path: '/dashboard', icon: 'fas fa-fw fa-tachometer-alt', subMenu: [] },
    { title: 'Polizas', path: '/polizas', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Autos', path: '/autos', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Clientes', path: '/clientes', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Usuarios', path: '/usuarios', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Upload', path: '/upload', icon: 'fas fa-fw fa-tachometer-alt', subMenu: [] },
    { title: 'Roles', path: '/roles', icon: 'fas fa-fw fa-tachometer-alt', subMenu: [] },
    { title: 'Paquete Caracteristicas', path: '/paquete_caracteristica', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Paquetes', path: '/paquetes', icon: 'fas fa-fw fa-tachometer-alt', subMenu: [] },
    { title: 'Modelo Año', path: '/model_año', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Modelo', path: '/modelos', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Marcas', path: '/marcas', icon: 'fas fa-fw fa-tachometer-alt', subMenu: [] },
    { title: 'Historico Pagos', path: '/historicos_pagos', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Cuentas por Cobrar', path: '/cuentas_por_cobrar', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Características', path: '/tipos_caracteristicas', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Ciudades', path: '/ciudades', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Característica', path: '/caracteristicas', icon: 'fas fa-fw fa-table', subMenu: [] },    
    { title: 'Aseguradoras', path: '/aseguradoras', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Administradores', path: '/administradores', icon: 'fas fa-fw fa-table', subMenu: [] },
    { title: 'Año', path: '/año', icon: 'fas fa-fw fa-table', subMenu: [] },
]
